services:
  garmin-fastapi-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: garmin-fastapi-bridge
    restart: always
    environment:
      - DEBUG=False
    ports:
      - 10821:8000
    volumes:
      - ./data:/opt/garmin/data
